#!/bin/bash

# Export paths here if necessary or recommended.
export LD_LIBRARY_PATH="/usr/lib64/mpich/lib":$LD_LIBRARY_PATH

# Load environment if this script is run directly.
if test "$CS_ENVIRONMENT_SET" != "true" ; then
  module purge
  module load openmpi/2.1.2
  module load mpich/3.2
  module load python/2.7
  module load mesa/18.0.1
  module load paraview/5.6.0
  module load openblas/0.2.20-single
  module load suitesparse/5.2.0
  module load fftw/3.3.6-single
  module load hdf5/1.8.18
  module load gnuplot/5.2.0
  module load sparsersb/1.2.0
  module load octave/4.4.0
  module load llvm/6.0.0
  module load gcc/4.9.4
  module load python3/3.6.1
fi

export LD_LIBRARY_PATH="/share/apps/salome/8.5.0/BINARIES-CO6/med/lib":$LD_LIBRARY_PATH
export LD_LIBRARY_PATH="/share/apps/salome/8.5.0/BINARIES-CO6/cgns/lib":$LD_LIBRARY_PATH
export LD_LIBRARY_PATH="/share/storage/pub/finzeo/saturne-vof/lib":$LD_LIBRARY_PATH

export OMP_NUM_THREADS=1

cd /share/storage/finzeo/Simulaciones/GTS_StormsMaddox/Base/RESU/20230328-1001

# Run solver.
mpiexec -n 80 -ppn 20 ./cs_solver --mpi "$@"
export CS_RET=$?

exit $CS_RET
